import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_sa_blocks_icon_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_img_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_content_section_content_heading_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_contact_form_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_faq_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_map_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_blogs_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_services_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_sa_blocks_testimonial_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_icon_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_img_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_content_section_content_heading_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_contact_form_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_faq_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_map_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_blogs_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_services_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_service_blocks_testimonial_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_icon_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_img_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_content_section_content_heading_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_contact_form_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_faq_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_map_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_blogs_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_services_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_index_blocks_testimonial_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_icon_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_img_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_content_section_content_heading_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_contact_form_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_faq_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_map_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_blogs_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_services_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_about_blocks_testimonial_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_icon_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_img_cards_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_content_section_content_heading_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_contact_form_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_faq_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_map_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_blogs_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_services_grid_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  CREATE TYPE "public"."enum_s_area_blocks_testimonial_section_section_title_type" AS ENUM('H2', 'H3', 'H4', 'H5', 'H6');
  ALTER TABLE "sa_blocks_icon_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "sa_blocks_img_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "sa_blocks_contact_form_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "sa_blocks_faq_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "sa_blocks_map_section" RENAME COLUMN "heading" TO "section_title_heading";
  ALTER TABLE "sa_blocks_blogs_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "sa_blocks_services_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "sa_blocks_testimonial_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_icon_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_img_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_contact_form_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_faq_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_map_section" RENAME COLUMN "heading" TO "section_title_heading";
  ALTER TABLE "service_blocks_blogs_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_services_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "service_blocks_testimonial_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_icon_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_img_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_contact_form_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_faq_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_map_section" RENAME COLUMN "heading" TO "section_title_heading";
  ALTER TABLE "index_blocks_blogs_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_services_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "index_blocks_testimonial_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_icon_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_img_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_contact_form_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_faq_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_map_section" RENAME COLUMN "heading" TO "section_title_heading";
  ALTER TABLE "about_blocks_blogs_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_services_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "about_blocks_testimonial_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_icon_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_img_cards_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_contact_form_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_faq_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_map_section" RENAME COLUMN "heading" TO "section_title_heading";
  ALTER TABLE "s_area_blocks_blogs_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_services_grid_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "s_area_blocks_testimonial_section" RENAME COLUMN "title" TO "section_title_title";
  ALTER TABLE "blog" ADD COLUMN "meta_json_l_d" jsonb;
  ALTER TABLE "sa_blocks_icon_cards_grid_section" ADD COLUMN "section_title_type" "enum_sa_blocks_icon_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_img_cards_grid_section" ADD COLUMN "section_title_type" "enum_sa_blocks_img_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_content_section" ADD COLUMN "content_heading_type" "enum_sa_blocks_content_section_content_heading_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_contact_form_section" ADD COLUMN "section_title_type" "enum_sa_blocks_contact_form_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_faq_section" ADD COLUMN "section_title_type" "enum_sa_blocks_faq_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_map_section" ADD COLUMN "section_title_type" "enum_sa_blocks_map_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_blogs_grid_section" ADD COLUMN "section_title_type" "enum_sa_blocks_blogs_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_services_grid_section" ADD COLUMN "section_title_type" "enum_sa_blocks_services_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa_blocks_testimonial_section" ADD COLUMN "section_title_type" "enum_sa_blocks_testimonial_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "sa" ADD COLUMN "meta_json_l_d" jsonb;
  ALTER TABLE "service_blocks_icon_cards_grid_section" ADD COLUMN "section_title_type" "enum_service_blocks_icon_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_img_cards_grid_section" ADD COLUMN "section_title_type" "enum_service_blocks_img_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_content_section" ADD COLUMN "content_heading_type" "enum_service_blocks_content_section_content_heading_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_contact_form_section" ADD COLUMN "section_title_type" "enum_service_blocks_contact_form_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_faq_section" ADD COLUMN "section_title_type" "enum_service_blocks_faq_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_map_section" ADD COLUMN "section_title_type" "enum_service_blocks_map_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_blogs_grid_section" ADD COLUMN "section_title_type" "enum_service_blocks_blogs_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_services_grid_section" ADD COLUMN "section_title_type" "enum_service_blocks_services_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service_blocks_testimonial_section" ADD COLUMN "section_title_type" "enum_service_blocks_testimonial_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "service" ADD COLUMN "meta_json_l_d" jsonb;
  ALTER TABLE "index_blocks_icon_cards_grid_section" ADD COLUMN "section_title_type" "enum_index_blocks_icon_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_img_cards_grid_section" ADD COLUMN "section_title_type" "enum_index_blocks_img_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_content_section" ADD COLUMN "content_heading_type" "enum_index_blocks_content_section_content_heading_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_contact_form_section" ADD COLUMN "section_title_type" "enum_index_blocks_contact_form_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_faq_section" ADD COLUMN "section_title_type" "enum_index_blocks_faq_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_map_section" ADD COLUMN "section_title_type" "enum_index_blocks_map_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_blogs_grid_section" ADD COLUMN "section_title_type" "enum_index_blocks_blogs_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_services_grid_section" ADD COLUMN "section_title_type" "enum_index_blocks_services_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index_blocks_testimonial_section" ADD COLUMN "section_title_type" "enum_index_blocks_testimonial_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "index" ADD COLUMN "meta_json_l_d" jsonb;
  ALTER TABLE "about_blocks_icon_cards_grid_section" ADD COLUMN "section_title_type" "enum_about_blocks_icon_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_img_cards_grid_section" ADD COLUMN "section_title_type" "enum_about_blocks_img_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_content_section" ADD COLUMN "content_heading_type" "enum_about_blocks_content_section_content_heading_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_contact_form_section" ADD COLUMN "section_title_type" "enum_about_blocks_contact_form_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_faq_section" ADD COLUMN "section_title_type" "enum_about_blocks_faq_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_map_section" ADD COLUMN "section_title_type" "enum_about_blocks_map_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_blogs_grid_section" ADD COLUMN "section_title_type" "enum_about_blocks_blogs_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_services_grid_section" ADD COLUMN "section_title_type" "enum_about_blocks_services_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about_blocks_testimonial_section" ADD COLUMN "section_title_type" "enum_about_blocks_testimonial_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "about" ADD COLUMN "meta_json_l_d" jsonb;
  ALTER TABLE "s_area_blocks_icon_cards_grid_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_icon_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_img_cards_grid_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_img_cards_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_content_section" ADD COLUMN "content_heading_type" "enum_s_area_blocks_content_section_content_heading_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_contact_form_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_contact_form_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_faq_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_faq_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_map_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_map_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_blogs_grid_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_blogs_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_services_grid_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_services_grid_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area_blocks_testimonial_section" ADD COLUMN "section_title_type" "enum_s_area_blocks_testimonial_section_section_title_type" DEFAULT 'H2' NOT NULL;
  ALTER TABLE "s_area" ADD COLUMN "meta_json_l_d" jsonb;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "sa_blocks_icon_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "sa_blocks_img_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "sa_blocks_contact_form_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "sa_blocks_faq_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "sa_blocks_map_section" RENAME COLUMN "section_title_heading" TO "heading";
  ALTER TABLE "sa_blocks_blogs_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "sa_blocks_services_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "sa_blocks_testimonial_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_icon_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_img_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_contact_form_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_faq_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_map_section" RENAME COLUMN "section_title_heading" TO "heading";
  ALTER TABLE "service_blocks_blogs_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_services_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "service_blocks_testimonial_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_icon_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_img_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_contact_form_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_faq_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_map_section" RENAME COLUMN "section_title_heading" TO "heading";
  ALTER TABLE "index_blocks_blogs_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_services_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "index_blocks_testimonial_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_icon_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_img_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_contact_form_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_faq_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_map_section" RENAME COLUMN "section_title_heading" TO "heading";
  ALTER TABLE "about_blocks_blogs_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_services_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "about_blocks_testimonial_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_icon_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_img_cards_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_contact_form_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_faq_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_map_section" RENAME COLUMN "section_title_heading" TO "heading";
  ALTER TABLE "s_area_blocks_blogs_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_services_grid_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "s_area_blocks_testimonial_section" RENAME COLUMN "section_title_title" TO "title";
  ALTER TABLE "blog" DROP COLUMN IF EXISTS "meta_json_l_d";
  ALTER TABLE "sa_blocks_icon_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_img_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_content_section" DROP COLUMN IF EXISTS "content_heading_type";
  ALTER TABLE "sa_blocks_contact_form_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_faq_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_map_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_blogs_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_services_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa_blocks_testimonial_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "sa" DROP COLUMN IF EXISTS "meta_json_l_d";
  ALTER TABLE "service_blocks_icon_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_img_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_content_section" DROP COLUMN IF EXISTS "content_heading_type";
  ALTER TABLE "service_blocks_contact_form_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_faq_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_map_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_blogs_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_services_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service_blocks_testimonial_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "service" DROP COLUMN IF EXISTS "meta_json_l_d";
  ALTER TABLE "index_blocks_icon_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_img_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_content_section" DROP COLUMN IF EXISTS "content_heading_type";
  ALTER TABLE "index_blocks_contact_form_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_faq_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_map_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_blogs_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_services_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index_blocks_testimonial_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "index" DROP COLUMN IF EXISTS "meta_json_l_d";
  ALTER TABLE "about_blocks_icon_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_img_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_content_section" DROP COLUMN IF EXISTS "content_heading_type";
  ALTER TABLE "about_blocks_contact_form_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_faq_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_map_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_blogs_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_services_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about_blocks_testimonial_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "about" DROP COLUMN IF EXISTS "meta_json_l_d";
  ALTER TABLE "s_area_blocks_icon_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_img_cards_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_content_section" DROP COLUMN IF EXISTS "content_heading_type";
  ALTER TABLE "s_area_blocks_contact_form_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_faq_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_map_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_blogs_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_services_grid_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area_blocks_testimonial_section" DROP COLUMN IF EXISTS "section_title_type";
  ALTER TABLE "s_area" DROP COLUMN IF EXISTS "meta_json_l_d";
  DROP TYPE "public"."enum_sa_blocks_icon_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_img_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_content_section_content_heading_type";
  DROP TYPE "public"."enum_sa_blocks_contact_form_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_faq_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_map_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_blogs_grid_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_services_grid_section_section_title_type";
  DROP TYPE "public"."enum_sa_blocks_testimonial_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_icon_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_img_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_content_section_content_heading_type";
  DROP TYPE "public"."enum_service_blocks_contact_form_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_faq_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_map_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_blogs_grid_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_services_grid_section_section_title_type";
  DROP TYPE "public"."enum_service_blocks_testimonial_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_icon_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_img_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_content_section_content_heading_type";
  DROP TYPE "public"."enum_index_blocks_contact_form_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_faq_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_map_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_blogs_grid_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_services_grid_section_section_title_type";
  DROP TYPE "public"."enum_index_blocks_testimonial_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_icon_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_img_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_content_section_content_heading_type";
  DROP TYPE "public"."enum_about_blocks_contact_form_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_faq_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_map_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_blogs_grid_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_services_grid_section_section_title_type";
  DROP TYPE "public"."enum_about_blocks_testimonial_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_icon_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_img_cards_grid_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_content_section_content_heading_type";
  DROP TYPE "public"."enum_s_area_blocks_contact_form_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_faq_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_map_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_blogs_grid_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_services_grid_section_section_title_type";
  DROP TYPE "public"."enum_s_area_blocks_testimonial_section_section_title_type";`)
}
